DEBUG = true;

S1_NAME = 'Stage 1 - Repeat after me.'

//SCREEN SIZE
SCREEN_WIDTH = 1200;
SCREEN_HEIGHT = 600;

//GAME PATH
GAME_PATH = 'js/game/';

//ASSETS
COMMON_ASSETS = 'assets/'

AUDIO_ASSETS = COMMON_ASSETS + 'audio/';
BACKGROUND_ASSETS = COMMON_ASSETS + 'backgrounds/';
BUTTON_ASSETS = COMMON_ASSETS + 'buttons/';
CHARS_ASSETS = COMMON_ASSETS + 'characters/';
DIALOGS_ASSETS = COMMON_ASSETS + 'dialogs/';
FONTS_ASSETS = COMMON_ASSETS + 'fonts/';
TIMERS_ASSETS = COMMON_ASSETS + 'timers/';

NOKIA_BLACK_NAME = 'nokia_black';
NOKIA_BLACK_PATH = FONTS_ASSETS + 'nokia16black.png';
NOKIA_BLACK_ATLAS = FONTS_ASSETS + 'nokia16black.xml';

NOKIA_WHITE_NAME = 'nokia_white';
NOKIA_WHITE_PATH = FONTS_ASSETS + 'nokia.png';
NOKIA_WHITE_ATLAS = FONTS_ASSETS + 'nokia.xml';

DEFAULT_DIALOG_FONT = NOKIA_BLACK_NAME;
DEFAULT_FONT_SIZE = 30;

BLACKBOARD_TEXT_POSITION_X = 350;
BLACKBOARD_TEXT_POSITION_Y = 50;

//BACKGROUNDS
BACKGROUND_NAME = 'background'
BACKGROUND_PATH = BACKGROUND_ASSETS + 'backgrounds.png';
BACKGROUND_ATLAS = BACKGROUND_ASSETS + 'backgrounds.json';

BACKGROUND_CLASSROOM_NAME = 'classroom';
BACKGROUND_FADER_NAME = 'transparent_layer';
BACKGROUND_BLACKBOARD_NAME = 'blackboard';

BACKGROUND_POSITION_X = 0;
BACKGROUND_POSITION_Y = 0;

//TEACHER
TEACHER_NAME = 'teacher';
TEACHER_PATH = CHARS_ASSETS + 'teacher/' + 'teacher.png';
TEACHER_ATLAS = CHARS_ASSETS + 'teacher/' + 'teacher.json';

TEACHER_HELLO_NAME = 'hello';
TEACHER_POINTING_NAME = 'say_this';
TEACHER_SPEAKING = 'speaking';
TEACHER_YOUR_TURN = 'your_turn';
TEACHER_ONE_LAST_TIME = 'one_last_time';
TEACHER_WELL_DONE = 'well_done';

this.random_repeat_frame = function()
{
	if((Math.floor(Math.random() * 3)) == 0)
	{
		return TEACHER_YOUR_TURN;
	}
	else
	{
		return TEACHER_ONE_LAST_TIME;
	}
}

//MICRO
MICRO_NAME = 'micro';
MICRO_PATH = AUDIO_ASSETS + 'micro/' + 'micro.png';
MICRO_ATLAS = AUDIO_ASSETS + 'micro/' + 'micro.json';

MICRO_OFF = 'off';
MICRO_ON_NO_DETECTION = 'on_no_detection';
MICRO_ON_DETECTION = 'on_voice_detection';

//TIMERS
TIMER_NAME = 'timer';
TIMER_PATH = TIMERS_ASSETS + 'timer.png';
TIMER_ATLAS = TIMERS_ASSETS + 'timer.json';

TIMER_BAR_NAME = 'bar';
TIMER_BACKGROUND_NAME = 'background';

//DIALOG BUBBLE
DIALOG_NAME = 'dialog';
DIALOG_PATH = DIALOGS_ASSETS + 'dialogs.png';
DIALOG_ATLAS = DIALOGS_ASSETS + 'dialogs.json';

BIG_SQUARE_DIALOG_NAME = 'big_square';
BIG_SQUARE_DIALOG_WIDTH = 570;
BIG_SQUARE_DIALOG_POSITION_X = 320;
BIG_SQUARE_DIALOG_POSITION_Y = 40;
BIG_SQUARE_DIALOG_CONTENT_OFFSET = 30;
BIG_SQUARE_DIALOG_CONTENT_X = BIG_SQUARE_DIALOG_POSITION_X + BIG_SQUARE_DIALOG_CONTENT_OFFSET;
BIG_SQUARE_DIALOG_CONTENT_Y = BIG_SQUARE_DIALOG_POSITION_Y + BIG_SQUARE_DIALOG_CONTENT_OFFSET;

BOTTOM_DIALOG_NAME = 'bottom';
BOTTOM_DIALOG_POSITION_X = 0;
BOTTOM_DIALOG_POSITION_Y = 0;
BOTTOM_DIALOG_CONTENT_X = 350;
BOTTOM_DIALOG_CONTENT_Y = 480;

SMALL_DIALOG_NAME = 'small';
SMALL_DIALOG_POSITION_X = 0;
SMALL_DIALOG_POSITION_Y = 0;
SMALL_DIALOG_CONTENT_X = 350;
SMALL_DIALOG_CONTENT_Y = 155;


//BUTTONS
BUTTONS_SPRITESHEET = 'buttons';
BUTTONS_ATLAS = BUTTON_ASSETS + 'buttons.png';
BUTTONS_WIDTH = 224;
BUTTONS_HEIGHT = 50;
BUTTON_NORMAL = 2;
BUTTON_HOVER = 1;
BUTTON_CLICK = 1;

BUTTONS_FONT = NOKIA_BLACK_NAME;
BUTTONS_FONT_SIZE = 20;

DEFAULT_BUTTON_CONTENT = '> ';

//STAGE
CURRENT_STAGE = null;

this.next_stage = function()
{
	CURRENT_STAGE = new Stage1();
	CURRENT_STAGE.run();
}

//ALPHA VALUES
TRANSPARENT = 0;
OPAQUE = 1;
