S1_NAME = 'Stage 1 - Repeat after me.'

S1_TEACHER_INITIAL_POSITION_X = -415;
S1_TEACHER_INITIAL_POSITION_Y = 135;

S1_LISTEN_BUTTON_CONTENT = 'Listen';
S1_REPEAT_BUTTON_CONTENT = 'Repeat';
S1_NEXT_STAGE_BUTTON_CONTENT = 'Next stage';

S1_BOTTOM_DIALOG_CONTENT = 'Repeat after me.';

S1_BUTTON_LISTEN_POSITION_X = 600;
S1_BUTTON_LISTEN_POSITION_Y = 470;

S1_SMALL_DIALOG_00 = 'Your turn!';
S1_SMALL_DIALOG_05 = 'WELL DONE!';

S1_MICRO_POSITION_X = 645;
S1_MICRO_POSITION_Y = 535;

S1_CURRENT_SENTENCE = 'things';

S1_TOTAL_TIME = 10;